sudo: required
services:
  - docker

before_install:
  - docker build -t ledishzj/docker-react -f Dockerfile.dev .

script:
  - docker run ledishzj/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region:
  app:
  env:
  bucket_name:
  bucket_path:
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "AWS_SECRET_KEY"